# Apache
ROUNDCUBE_SERVER_ADMIN: webmaster@example.org

ROUNDCUBE_KEEP_INSTALLER: true

# Self signed certificat will be generated
# if ROUNDCUBE_HTTPS is set to true and no certificat and key are provided.

# To use your custom certificat and key 2 options :
# - add them in service/roundcube/assets/apache2/ssl and build the image
# - or during docker run mount a data volume with those files to /container/service/roundcube/apache2/ssl
ROUNDCUBE_HTTPS: true
ROUNDCUBE_HTTPS_CRT_FILENAME: roundcube.crt
ROUNDCUBE_HTTPS_KEY_FILENAME: roundcube.key
ROUNDCUBE_HTTPS_CA_CRT_FILENAME: ca.crt


# LDAP client tls config
ROUNDCUBE_LDAP_CLIENT_TLS: false
ROUNDCUBE_LDAP_CLIENT_TLS_REQCERT: demand
ROUNDCUBE_LDAP_CLIENT_TLS_CA_CRT_FILENAME: ldap-ca.crt
ROUNDCUBE_LDAP_CLIENT_TLS_CRT_FILENAME: ldap-client.crt
ROUNDCUBE_LDAP_CLIENT_TLS_KEY_FILENAME: ldap-client.key

# MARIADB client tls config
ROUNDCUBE_MARIADB_CLIENT_TLS: false
ROUNDCUBE_MARIADB_CLIENT_TLS_CA_CRT_FILENAME: database-ca.crt
ROUNDCUBE_MARIADB_CLIENT_TLS_CRT_FILENAME: database-client.crt
ROUNDCUBE_MARIADB_CLIENT_TLS_KEY_FILENAME: database-client.key

ROUNDCUBE_CFSSL_PREFIX: roundcube
LDAP_CLIENT_CFSSL_PREFIX: ldapclient
MARIADB_CLIENT_CFSSL_PREFIX: database
